config/routes.rb
Rails.application.routes.draw do
    resources :users 
    resources :tweets
    resources :likes
    post 'top/login'
    get 'top/logout'
    get 'top/main'
    root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :like_users, source: :user, through: :likes
    
    validates :message, presence: true
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy #ユーザを消すとツイートも消える
    has_many :likes, dependent: :destroy #ユーザを消すといいねも消える
    has_many :like_tweets, source: :tweet, through: :likes

    validates :uid,  presence: true
    validates :uid, uniqueness: true
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation

    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
            tweet.like(current_user)
        end
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        render 'login_form'
    end
    
    def login
        if user = User.find_by(uid: params[:uid]) and BCrypt::Password.new(user.pass) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to root_path 
        else
            render 'login_form'
        end

    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end
    
    def new
        @tweets = Tweet.new
    end
    
    def create
        @tweets = Tweet.new(message: params[:tweet][:message],  user_id: current_user.id)
        if @tweets.save
            redirect_to root_path
        else
            render new_tweet_path
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def new
        @users = User.new
    end
    
    def create
        @user = User.new(
            uid: params[:user][:uid],
            password: params[:user][:password],
            password_confirmation: params[:user][:password_confirmation])
        if @user.save
            redirect_to users_path
        else
            render 'new'
        end
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p>
      <% if current_user %>
        ログイン中(<%= current_user.uid %>)さん
      <% else %>
        ログインしてません
      <% end %>
    </p>
  </body>
</html>

app/views/top/login_form.html.erb
<%= form_tag top_login_path, method: :post do %>
    <%= label_tag :uid, 'ユーザーID：' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード：' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

<br><%= link_to '戻る', root_path %>

app/views/tweets/index.html.erb
<p>
    <% if current_user %>
        <%= link_to 'ツイートする', new_tweet_path %>
    <% end %>
</p>

<% @tweets.each do |tweet| %>
    <p>
        <%= tweet.message %>
        
        <% if current_user %>
            <% if  tweet.likes.find_by(user_id: current_user.id) %>
                <%= link_to 'いいね削除', like_path(tweet), method: :delete %>
            <% else %>
                <%= link_to 'いいね', likes_path(tweet_id: tweet.id), method: :post %>
            <% end %>
        <% end %>

        <% if current_user and tweet.user_id == current_user.id %>
            <%= link_to 'ツイートを削除', tweet_path(tweet) , method: :delete %>
        <% end %>
    </p>
<% end %>


<p>
    <% if current_user %>
        <%= link_to 'ログアウト', top_logout_path %>
    <% else %>
        <%= link_to 'ログイン', top_main_path %>
    <% end %>
</p>

<p>
    <%= link_to 'ユーザー一覧', users_path %>
</p>

app/views/tweets/new.html.erb
<% if @tweets.errors.present? %>
    <p>エラーがあります。<p>
    <ul>
        <% @tweets.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @tweets , url: {action: :create} do |f| %>
    <%= f.label :message, 'メッセージ：' %>
    <%= f.text_field :message %>
    <%= f.submit 'ツイート' %>
<% end %>

<br><%= link_to 'ツイート一覧に戻る', root_path %>

app/views/users/edit.html.erb
<% if @user.errors.present? %>
    <p>エラーがあります。<p>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @user , url: {action: :update} do |f| %>
    <%= f.label :uid, 'ユーザーID：' %>
    <%= f.text_field :uid %>
    <%= f.label :sentence, '紹介文' %>
    <%= f.text_field :sentence %>
    <%= f.submit 'ユーザー情報変更' %>
<% end %>

<br><%= link_to 'ユーザー一覧に戻る', users_path %>

app/views/users/index.html.erb
<%= link_to '新規登録', new_user_path %>

<% @users.each do |user| %>
<p>
    <%= user.uid%>
    <%= user.pass%>
    <%= link_to '削除', user_path(user) ,method: :delete %>
</p>
<% end %>

<br><%= link_to 'ツイート一覧に戻る', root_path %>

app/views/users/new.html.erb
<% if @users.errors.present? %>
    <p>エラーがあります。<p>
    <ul>
        <% @users.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @users , url: {action: :create} do |f| %>
    <%= f.label :uid, 'ID：' %>
    <%= f.text_field :uid %>
    <p>
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation %>
    </p>
    <%= f.submit '登録' %>
<% end %>

<br><%= link_to 'ユーザー一覧に戻る', users_path %>

app/views/users/show.html.erb
ユーザーID：<%= @user.uid %><br>
プロフィール文：<%= @user.sentence %>

<br><br><%= link_to '編集', "/users/#{@user.id}/edit" %>
<br><%= link_to 'ツイート一覧に戻る', root_path %>